#!/usr/bin/env bash
### Usage:
###   check-if-ship-exists <ship_name>
### Options:
###   --help
###
### upstart support script
### check if ship exists

#--HEAD--
SCRIPT="$(readlink -e -- "${0}")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")/.."
source "${SCRIPT_DIR}/main.source"
#--/HEAD--

if [[ -z "${ship_name}" ]]; then
  fatal "missing ship name"
fi
if ! hull_exists "${ship_name}"; then
  fatal "invalid ship name: '${ship_name}'"
fi
