#!/usr/bin/env bash
### Usage:
###   starphleet-container-jettison [--min_age=<minutes>] [--execute]
### Options:
###   --help
###   --min_age=<minutes>  [default: 720] Minimum age a container has to be before it is ever jettisoned.
###   --execute            Without this option, only the jettison plan will be displayed
###
### Jettison all unused containers from the ship
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"
SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

CANDIDATES="$(starphleet-container-inspection --min_age="${min_age}" "$(containers_currently_stopped)")"

# destroy containers that qualify
for CANDIDATE in ${CANDIDATES}; do
  warn "${SCRIPT_NAME}: destroying lxc ${CANDIDATE}"
  ${execute} && starphleet-lxc-destroy "${CANDIDATE}"
done
exit 0
