#!/usr/bin/env bash
### Usage:
###   assignment-stop <order>
### Options:
###   --help
###

#--HEAD--
SCRIPT="$(readlink -e -- "${0}")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/main.source"
#--/HEAD--

stop hyperdrive-assignment name="${order}"
