#!/usr/bin/env bash
### Usage:
###   buildpack-sync [--force]
### Options:
###   --help
###   --force   force a sync, even if there is a local buildpack

#--HEAD--
set -o nounset; set -o errexit
SCRIPT="$(test -L "$0" && readlink -e "$0" || readlink -e "$0")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/main.source"
#--/HEAD--

# NOTE: The assumption here for now is that the buildpacks are in GIT repos on GitHub
while read REPO; do
  # TODO: Need to make sure github does not use double byte chars and if they do
  # create a safe filename from the repo
  BUILDPACK="$(safe_repo_name "${REPO}")"
  BUILDPACK_PATH="${STARPHLEET_BUILDPACK_ROOT}/${BUILDPACK}"
  if [[ "${force}" == "true" || ! -d "${BUILDPACK_PATH}" ]]; then
    "${SCRIPT_DIR}/git-sync" "${REPO}" "${BUILDPACK_PATH}" || true
  fi
  trace "${REPO} available at ${BUILDPACK_PATH}"
done < "${STARPHLEET_BUILDPACK_MANIFEST}"
