#!/usr/bin/env bash
### Usage:
###   container-create
### Options:
###   --help
###
### Create the Starphleet base containers for workstations

#--HEAD--
set -o nounset; set -o errexit; set -o pipefail;
SCRIPT="$(test -L "$0" && readlink -e "$0" || readlink -e "$0")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/main.source"
#--/HEAD--

# TODO: figure out which log file the clone messages should go into
# TODO: lxc-attach failures are not sending out any messages
# TODO: clean up the path mess in here

#-- DEFAULT CONTAINER ----------------------------------------------------------

if container_exists 'starphleet'; then
  info "container 'starphleet' is missing and will now be created..."
  trace "log available at ${STARPHLEET_DATA_ROOT}/lxc-starphleet-create.log"
  (
    flock -x 200
    lxc-create --name="starphleet" --template="ubuntu" > "${STARPHLEET_DATA_ROOT}/lxc-starphleet-create.log" 2>&1
  ) 200>"${STARPHLEET_LOCKS}/lxc"
fi
info "container 'starphleet' ready"

source "${SCRIPT_DIR}/lib/workstation.source"

#-- BASE CONTAINER -------------------------------------------------------------

if container_exists 'starphleet-workstation'; then
  info "container 'starphleet-workstation' is missing and will now be created..."
  WORKSTATION_BASE="starphleet"
  WORKSTATION_NAME="starphleet-workstation"
  WORKSTATION_ROOT="${STARPHLEET_LXC_ROOT}/${WORKSTATION_NAME}"
  WORKSTATION_SHARE="${WORKSTATION_ROOT}/share"

  workstation_open
  cp "${STARPHLEET_ROOT}/setup/base-workstation-install.sh" "${WORKSTATION_SHARE}/setup.sh"
  cp "${STARPHLEET_ROOT}/setup/lxc-base.packages" "${WORKSTATION_SHARE}/lxc-base.packages"
  # TODO: Add a check here to see if the mount is properly setup
  trace "log available at ${WORKSTATION_ROOT}/setup.log"
  lxc-attach --name="starphleet-workstation" -- bash -c '/var/starphleet/share/setup.sh' > "${WORKSTATION_ROOT}/setup.log" 2>&1
  set +o xtrace
  workstation_close
fi
info "container 'starphleet-workstation' ready"
