#! /usr/bin/env bash
### Usage:
###   headquarters [--sync]
###   headquarters set <url> [--sync]
### Options:
###   <url>   GIT repo in the format of repo#branch
###   --help
###   --sync  Makes sure the HQ at <url> is up to date
###
### Not specifying any parameters outputs the current headquarters or an error message

# TODO: Try to make the order sync happen in parallel

#--HEAD--
SCRIPT="$(readlink -e -- "${0}")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/main.source"
#--/HEAD--

# set the headquarters
if [[ "${set}" == "true" ]]; then
  echo "export HYPERDRIVE_HQ='${url}'" > "${HYPERDRIVE_INCLUDES}/headquarters"
  export HYPERDRIVE_HQ="${url}"
fi
# status messages
if [ -n "${HYPERDRIVE_HQ:-}" ]; then
  info "Headquarters are set to ${HYPERDRIVE_HQ}"
else
  warn "Headquarters have not been set"
fi
# sync the headquarters
if [[ "${sync}" == "true" ]]; then
  if [[ -z "${HYPERDRIVE_HQ:-}" ]]; then
    fatal "Headquarters have to be set before sync can be performed"
  fi
  info "synching headquarters..."
  "${SCRIPT_DIR}/git-sync" "${HYPERDRIVE_HQ}" "${HYPERDRIVE_HQ_ROOT}" || true

  # pull new and existing order details
  for ORDER in $(orders_list); do
    LOCAL_ORDER_REPO="${HYPERDRIVE_ORDER_REPOS}/$(awk -F/ '{print $(NF-1)}' <<< "${ORDER}")"
    REMOTE_ORDER_REPO="$(awk '/^autodeploy[ \t]*/ {print $2}' "${ORDER}" | tail -1)"
    # TODO: Need error checking here for empty vars
    # TODO: Error check to handle invalid service repos, probably skip the update, but need to log it somehow
    info "synching '${LOCAL_ORDER_REPO}'..."
    "${SCRIPT_DIR}/git-sync" "${REMOTE_ORDER_REPO}" "${LOCAL_ORDER_REPO}" || true
  done
  # clean up orders that no longer exist
fi
