#!/usr/bin/env bash
# this script should be added to the she-bang (#!) section of all hyperdrive scripts
# it will make sure that the environment is in the proper state and handle common script headers

OVERSEER_SCRIPT="$(readlink -e -- "${0}")"
CURRENT_SCRIPT="$(readlink -e -- "${1}")"
CURRENT_SCRIPT_DIR="$(dirname "${CURRENT_SCRIPT}")"
if [[ "$(basename ${OVERSEER_SCRIPT})" == 'overseer' && -z "${1}" ]]; then
  echo "cannot call overseer directly"
  exit 1
fi
shift

if [[ "$(id -u)" -ne "0" ]]; then 
  echo "you must be root to run this this script";
  exit 1
fi

set -o allexport

SCRIPT_NAME="$(basename "${CURRENT_SCRIPT}")"
SCRIPT_DIR="$(dirname "${OVERSEER_SCRIPT}")"
SCRIPT_FULL_PATH="${CURRENT_SCRIPT_DIR}/${SCRIPT_NAME}"

source "${SCRIPT_DIR}/main.source"

set +o allexport

bash "${SCRIPT_FULL_PATH}" $@
