#!/usr/bin/env bash
### Usage:
###   ship-decommission <ship_name>
### Options:
###   --help
###
### dismantle a ship completely

#--HEAD--
SCRIPT="$(readlink -e -- "${0}")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/main.source"
#--/HEAD--

lxc-destroy -f --name="${ship_name}"
