#!/usr/bin/env bash
### Usage:
###   ship-pilot <ship_name>
### Options:
###   --help
###
### work on a ship as the app operator

#--HEAD--
SCRIPT="$(readlink -e -- "${0}")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/main.source"
#--/HEAD--

lxc-attach --name="${ship_name}" -- su - ubuntu
