#!/usr/bin/env bash
### Usage:
###   ship-launch <workstation_name>
### Options:
###   --help
###   <workstation_name>    name of the workstation
###
### Starts service operations in a workstation

#--HEAD--
set -o nounset; set -o errexit; set -o pipefail;
SCRIPT="$(test -L "$0" && readlink -e "$0" || readlink -e "$0")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/main.source"
#--/HEAD--

if ! hull_exists "${workstation_name}"; then
  fatal "invalid container name '${workstation_name}'"
fi
lxc-attach --name "${workstation_name}" -- sudo -H -u ubuntu -i bash -c "./start.sh"
