#!/usr/bin/env bash
### Usage:
###   ship-pilot [<ship_name>]
### Options:
###   --help
###
### work on a ship as the app operator

#--HEAD--
SCRIPT="$(readlink -e -- "${0}")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/main.source"
#--/HEAD--


if [[ -z "${ship_name}" ]]; then
  SELECTION="$(lxc-ls --running -1 "^hyperdrive-.+-[\w]{8}-[\w]{7}$" | percol)"
  if [[ -n "${SELECTION}" ]]; then
    lxc-attach --name="${SELECTION}" -- su - ubuntu
  fi
else
  lxc-attach --name="${ship_name}" -- su - ubuntu
fi
