#!/usr/bin/env bash
### Usage:
###   ship-launch <hull_name> 
### Options:
###   --help

#--HEAD--
# TODO: See if this can be added from a template
set -o nounset; set -o errexit; set -o pipefail
SCRIPT="$(test -L "$0" && readlink -e "$0" || readlink -e "$0")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/main.source"
#--/HEAD--

if ! hull_exists "${hull_name}"; then
  echo "upstream ${hull_name} {" > "${UPSTREAM_CONF}"
  for IP_ADDRESS in $(lxc-ls --fancy | grep "^${container_group}" | awk '{ print $3; }')
  do
    echo "server ${IP_ADDRESS}:${container_port} max_fails=0;" >> "${UPSTREAM_CONF}"
  done
  echo "}" >> "${UPSTREAM_CONF}"
fi
