#!/usr/bin/env bash
### Usage:
###   ship-engage <hull_name>
### Options:
###   --help
###   <hull_name>    name of the ship
###
### Starts service operations in a ship

#--HEAD--
set -o nounset; set -o errexit; set -o pipefail;
SCRIPT="$(test -L "$0" && readlink -e "$0" || readlink -e "$0")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/main.source"
#--/HEAD--

if ! hull_exists "${hull_name}"; then
  fatal "invalid container name '${hull_name}'"
fi
lxc-attach --name "${hull_name}" -- sudo -H -u ubuntu -i bash -c "./start.sh"
