#! /usr/bin/env bash
### Usage:
###   starphleet-headquarters [<url>] [--sync]
### Options:
###   <url>   GIT repo in the format of repo#branch
###   --help
###   --sync  Makes sure the HQ at <url> is up to date
###
### Not specifying any parameters outputs the current headquarters or an error message

#--HEAD--
set -o nounset; set -o errexit
SCRIPT="$(test -L "$0" && readlink "$0" || echo "$0")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/starphleet-main.source"
#--/HEAD--

# status messages
if [[ -z "${url}" && "${sync}" == "false" ]]; then
  if [ -n "${STARPHLEET_HQ:-}" ]; then
    info "${SCRIPT_NAME}: Headquarters are set to ${STARPHLEET_HQ}"
    exit 0
  fi
  fatal "${SCRIPT_NAME}: Headquarters have not been set"
fi
# set the headquarters
if [[ -n "${url}" ]]; then
  echo "export STARPHLEET_HQ=\"${url}\"" > "${STARPHLEET_INCLUDES}/headquarters"
  export STARPHLEET_HQ="${url}"
  info "${SCRIPT_NAME}: Headquarters set to ${url}"
fi
# sync the headquarters
if [[ "${sync}" == "true" ]]; then
  if [[ -z "${STARPHLEET_HQ:-}" ]]; then
    fatal "${SCRIPT_NAME}: Headquarters have to be set before sync can be performed"
  fi
  info "${SCRIPT_NAME}: synching headquarters..."
  "${SCRIPT_DIR}/starphleet-git-synch" "${STARPHLEET_HQ}" "${STARPHLEET_HQ_ROOT}" || true
fi
