#!/usr/bin/env bash
### Usage:
###   starphleet-container-inspection --min_age=<minutes> <container_list>
### Options:
###   --help
###   --min_age=<minutes>  Minimum age a container should be in minutes
###
### Based on a list of containers, return the ones that are still in use, and past a certain age
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"
SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

function remove_first_list_from_second() {
  comm --output-delimiter=" " -23 <(echo -n "${1}" | sort) <(echo -n "${2}" | sort)
}

function compute_container_hash_from_order_file() {
  # ${1} - file path to a current starphleet order file
  ORDER_NAME="${1%/*}"; ORDER_NAME="${ORDER_NAME##*/}"
  ORDER_GIT="${1%/*}/git"

  get_CURRENT_SHA "${ORDER_GIT}"
  get_SHASUM "${1}"
  get_HASH "$(urlencode "${ORDER_NAME}").${SHASUM}.${CURRENT_SHA}.orders"
}

RECENTLY_ACTIVE="$(containers_created_recently "${min_age}")"
CANDIDATES=$(remove_first_list_from_second "${container_list}" "${RECENTLY_ACTIVE}")

# eliminate any candidates, that are in used in current orders
for ORDER_FILE in $(current_order_files)
do
  compute_container_hash_from_order_file "${ORDER_FILE}"
  CANDIDATES=$(grep -v "${HASH}" <(echo -n "${CANDIDATES}"))
done

echo "${CANDIDATES}"
