#!/usr/bin/env bash
### Usage:
###   status [--verbose]
### Options:
###   --help
###   --verbose   list more detailed output

#--HEAD--
SCRIPT="$(readlink -e -- "${0}")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/main.source"
#--/HEAD--

echo "hq   : ${HYPERDRIVE_HQ:-${C_RED}<not set>${C_RESET}}"

while IFS=$'\n' read ROW; do
  if [[ -z "${ROW}" ]]; then
    continue
  fi
  read NAME STATE IP <<< "${ROW}"

  case "${NAME}" in
    hyperdrive|hyperdrive-base-*|hyperdrive-basic-hull)
      case "${STATE}" in
        RUNNING) COLOR="${C_RED}" ;;
              *) COLOR="${C_GREEN}" ;;
      esac
      echo "lxc  : ${COLOR}${NAME}${C_RESET} [${STATE}] (${IP})"
      continue
  esac
  apply_order_exports "${HYPERDRIVE_LXC_ROOT}/${NAME}/share/orders"
  case "${STATE}" in
    RUNNING) echo "lxc  : ${C_GREEN}${NAME}${C_RESET} [${STATE}] (${IP}) '${PORT:-} ==> ${PUBLISH_PORT:-}'" ;;
    STOPPED) echo "lxc  : ${C_RED}${NAME}${C_RESET} [${STATE}] (${IP})" ;;
  esac
  MSG="$(< "${HYPERDRIVE_LXC_ROOT}/${NAME}/share/.msg")"
  echo "       ${C_BBLACK}- ${MSG}${C_RESET}"
done <<< "$(lxc-ls --fancy --fancy-format name,state,ipv4 "^hyperdrive" | tail -n +3)"

initctl list | grep -e "^hyperdrive" | awk '{print "job  :",$0}'

if [[ -n "${HYPERDRIVE_HQ:-}" ]]; then
  find "${HYPERDRIVE_HQ_ROOT}" -name "orders" -printf "%P " -exec \
    bash -c 'grep -e '^autodeploy' {} | tail -1 | awk '"'"'{print "order:",$2}'"'" \;  | awk '{print $2,"["$1"]",$3}'
fi
