#!/usr/bin/env bash
### Usage:
###   test
### Options:
###   --help
###
### hyperdrive test script for playing with bash stuff

#--HEAD--
SCRIPT="$(readlink -e -- "${0}")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/main.source"
#--/HEAD--

echo 
find "${HYPERDRIVE_HQ_ROOT}" -name "orders" -printf "%P " -exec bash -c 'grep -e '^autodeploy' {} | tail -1 | awk '"'"'{print "order:",$2}'"'" \; 
echo
find "${HYPERDRIVE_HQ_ROOT}" -name "orders" -printf "%P " -exec bash -c 'grep -e '^autodeploy' {} | tail -1 | awk '"'"'{print "order:",$2}'"'" \; | awk '{gsub(/\/orders$/, "", $1); print $2,"["$1"]",$3}'
echo
find "${HYPERDRIVE_HQ_ROOT}" -name "orders" -printf "%P " -exec bash -c 'grep -e '^autodeploy' {} | tail -1 | awk '"'"'{print "order:",$2}'"'" \; | statusFormatOrders.awk 
