#!/usr/bin/env bash
### Usage:
###   test word <name>
### Options:
###   --help
###
### hyperdrive test script for playing with bash stuff

#--HEAD--
SCRIPT="$(readlink -e -- "${0}")"
SCRIPT_NAME="$(basename "${SCRIPT}")"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
source "${SCRIPT_DIR}/main.source"
#--/HEAD--

info "name: ${name}"
info "word: ${word}"

sleep 10
